@startmindmap
center header 祖德留芳远，宗功世泽长
title 《王氏族谱》 金炉不断千年火  玉盏长明万世灯

* 十七世-王振(凤)德
** 十八世-王金团（长子）
** 十八世-王金圆（次子）
*** 十九世-王子河（长子）
**** 廿世-王维？（长子）
***** 廿一世-王宇（长子）
**** 廿世-王维军（次子）
***** 廿一世-王？？（长女）
***** 廿一世-王？？（次女）
*** 十九世-王子泉（次子）
**** 廿世-王振（长子）
***** 廿一世-王馨翌（长子）
**** 廿世-王斌（长女）
***** 廿一世-刘芷钰（长女）
**** 廿世-王冬升（次子）
***** 廿一世-王思勇（长子）
*** 十九世-王？？（长女）
**** 廿世-张福昌（长子）
**** 廿世-二娃（次子女）
**** 廿世-小霞（长女）
*** 十九世-王？？（次女）
**** 廿世-大姐（长女）
**** 廿世-二姐（次女）
**** 廿世-祥毅（长子）
*** 十九世-王？？（三女）

caption 参天之树，必有其根；怀山之水，必有其源；炎黄同心，华夏一脉；血浓于水，叶落归根；
center footer 祖德宗功流芳远,子孝孙贤世泽长
@endmindmap

## 迁徙溯源
- 薛城-小庄-->
- 薛城-火山头-->
- 滕州羊庄镇-大赵庄-->
- 滕州柴胡店镇-->开染坊分家
    - 滕州柴胡店镇-柴胡店村
    - 滕州柴胡店镇-郝庄村
    - 薛城陶庄镇-东仓存

## 祖坟方位
- 太爷-北官庄：东北西南向
- 爷爷-郝庄村西南：坐北朝南向

## 新续家谱字辈
至廿世，原家谱撰字辈已使用完，遂新续家谱字辈二十八字，以传后世。
- 开元宪立衍（延）吉庆
- 传家永昌思景隆
- 敬修厚德百福田
- 积善（鸿运）贵宝玉成山

## 祖制称呼
一般至上九代，下九代
鼻祖、远祖、太祖、烈祖、天祖、高祖、曾祖、祖父、父亲、
自己、
儿子、孙子、曾（重）孙、玄孙、来孙、弟孙、乃孙、云孙、耳孙

## 兄弟称呼
同父母：胞兄弟（二服）
同祖父：叔兄弟（三服）
同曾祖、同高祖：堂兄弟（四服、五服）

## 修家谱的意义
(1)、家谱是中国五千年文明史的见证，也是一种独特的文化传承。
(2)、号称是人生三大终极问题的：“我是谁，我从哪里来，我到哪里去“，自古以来一直困扰着众多的哲学家和宗教家，而家谱可能就是中国人以这样一种独特的方式，在一定程度上回答了这个问题。我是谁——姓氏源流，我从哪里来——世系谱，我到哪里去——家族坟茔和祠堂。
(3)、现代编修家谱仍然有着一定积极意义，可以增强家族和集体认同感，增强人与人之间的亲情联系，提升民族自豪感和文化自信等。
(4)、另外，家谱也是具有一定文学、社会、史料价值的，可以作为正史有益补充，留作以后的历史研究资料。

## 家谱主要内容
1、谱序
稍具规模的家谱，卷首一定会有一篇至几十篇不等的序文，它是每部家谱不可缺少的内容之一。
谱序包括新序、旧序、族外人的客序、跋语、目录和刻印人名以及其它关于本族的记述。

2、凡例
主要是阐述家谱的纂修原则和体例。
一般而言，一些家谱在每一次续修时都会订出若干条适合社会潮流与需要的规则，以作为修谱时所要遵循的原则。
家谱是中国几千历史传承下来的，自然会存在不少封建朝代的落后思想和陈规陋习，在编修家谱时，要注意摒弃一些不好的东西。重点是剔除旧家谱中的封建伦理道德思想和宗法观念，不能攀附假托。

3.姓氏源流
中国家谱素来有'叙本系，述始封'的传统，明清以来各家谱也大多有记姓氏源流的一章，或称姓氏源流，或称宗族源流。
它主要是用来记述本姓来源、本族的历史渊源、始祖、世派、迁徙、各支派间关系甚至改姓的原委等。

4.族规
是宗族家族成员共同制定的、用以约束和教化族人的宗族法规，是家谱中的重要组成部分。
其名称各异，种类很多，诸如家规、家戒、家法、家礼、族规、族约、祠规、戒谕等。

5.祠堂
记载宗族、家族祠堂修建的历史，介绍祠堂的建筑规模、地理位置，堂号及来源，收录有关祠堂的碑文、诗文、祠联、祠匾、祠堂图，建祠捐资人名，记录祠堂内神位世次、配享、附享、祭祀情况等。

6.世系图
世系图是家谱中的主体部分，又称为世系考、世系记等。这部分内容为所有家谱所共有，世系图用来清楚地记载每一个家族成员之间的相互关系与繁衍发展。使用较多的世系图模式有欧式、苏式、宝塔式和牒记式四种
不管采用什么样的世系图，通常都要记述以下内容：身之所出；姓名 性别 字辈 生 殁时间等；婚姻状况；子女状况等。
（名、字、号、生、死、葬、学、衔、职、婚、嫁、育）

7.传记
家谱中的传记又称行状、行述、志略等，其体裁有传记、行状、寿文、贺序、墓志、祭文以及抄自史传中的资料，主要载录家族成员中德行高尚、功成名就或某些方面影响较大的人等的事迹和传记资料。

8.字辈谱
又称派语、派行诗、行第、派引、排行等，专门登载族内成员姓名排行的字语。

10.捐修人员
家谱的编修或续修，是家族中的一件大事，涉及族中许多人员，耗时耗力，需要较大的投入，故经常要动员全族成员捐款助修。
一般修谱的惯例是：三十年一小修、六十年一大修


